# Generated by Django 4.2.7 on 2026-06-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_add_domain_scores'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analyticsexamevent',
            new_name='analytics_a_exam_ty_05d405_idx',
            old_name='analytics_a_exam_ty_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticssession',
            new_name='analytics_a_created_394272_idx',
            old_name='analytics_a_created_e4e7c8_idx',
        ),
    ]
