# Generated by Django 4.2.7 on 2026-01-10 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(help_text='Firebase user UID', max_length=128)),
                ('user_name', models.CharField(help_text='User display name', max_length=100)),
                ('user_photo_url', models.URLField(blank=True, help_text='User profile picture URL', max_length=500)),
                ('user_email', models.EmailField(blank=True, help_text='User email (optional)', max_length=254)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating from 1 to 5 stars')),
                ('comment', models.TextField(help_text="User's review comment")),
                ('exam_score', models.IntegerField(blank=True, help_text="User's exam score percentage", null=True)),
                ('passed', models.BooleanField(blank=True, help_text='Whether user passed the exam', null=True)),
                ('is_approved', models.BooleanField(default=True, help_text='Approved reviews appear on homepage')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured reviews shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='exams.exam')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_approved', '-created_at'], name='approved_reviews_idx'), models.Index(fields=['exam', 'rating'], name='exam_rating_idx')],
                'unique_together': {('user_uid', 'exam')},
            },
        ),
    ]
