# Generated by Django 4.2.7 on 2026-03-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedLecturePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus', models.CharField(db_index=True, max_length=50, unique=True)),
                ('syllabus_label', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('lectures', models.JSONField()),
                ('provider', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cached Lecture Plan',
                'verbose_name_plural': 'Cached Lecture Plans',
            },
        ),
        migrations.CreateModel(
            name='PinnedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(db_index=True, max_length=200)),
                ('syllabus', models.CharField(max_length=50)),
                ('lecture_plan', models.JSONField()),
                ('chat_messages', models.JSONField(default=list)),
                ('pinned_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pinned Plan',
                'verbose_name_plural': 'Pinned Plans',
                'indexes': [models.Index(fields=['user_uid', 'syllabus'], name='pinned_plan_user_syllabus_idx')],
                'unique_together': {('user_uid', 'syllabus')},
            },
        ),
    ]
