# Generated by Django 4.2.7 on 2026-06-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_add_exam_attempt'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cachedchatresponse',
            name='unique_syllabus_question_hash',
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('solutions_architect', 'AWS Solutions Architect'), ('cloud_practitioner', 'AWS Cloud Practitioner'), ('developer', 'AWS Developer'), ('sysops', 'AWS SysOps Administrator'), ('security', 'AWS Security Specialty'), ('machine_learning', 'AWS Machine Learning'), ('python', 'Python Programming'), ('prompt_engineering', 'Prompt Engineering')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='cachedchatresponse',
            unique_together={('syllabus', 'question_hash')},
        ),
    ]
