# Generated by Django 4.2.7 on 2026-07-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_remove_cachedchatresponse_unique_syllabus_question_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('solutions_architect', 'AWS Solutions Architect'), ('cloud_practitioner', 'AWS Cloud Practitioner'), ('developer', 'AWS Developer'), ('devops', 'AWS DevOps Engineer'), ('sysops', 'AWS SysOps Administrator'), ('security', 'AWS Security Specialty'), ('machine_learning', 'AWS Machine Learning'), ('python', 'Python Programming'), ('prompt_engineering', 'Prompt Engineering')], max_length=50),
        ),
    ]
